name: Update monkeytype theme json list

on:
  push:
    branches: [ themeList-action-dev ]

# on:
#   schedule:
#     - cron: '0 */6 * * *'

jobs:
  make-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
        
      - name: Download theme json file from monkeytype
        run: curl -o theme/themes.json https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/themes/_list.json
      
      - name: Print json file contents
        run: cat theme/themes.json
        
      - name: Update theme list 
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            let monkeytypeThemesJson = fs.readFileSync('themes.json');
            const filePath = '${{ github.workspace }}/theme/themes.json';
            fs.writeFileSync(filePath, monkeytypeThemesJson);
            
      - name: Print updated theme contents
        run: |
          cat theme/themes.json
          
      - name: Configure git
        run: |
          git config --global user.name "ridemountainpig"
          git config --global user.email "lin0905580802@gmail.com"
          
      - name: Commit and push changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected."
          else
            git add .
            git commit -m "feat: update themes json list"
          fi
        continue-on-error: true
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: themeList-action-dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
