name: Update monkeytype theme json list

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  make-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        
      - name: Download theme json file from monkeytype
        run: wget --timeout=180 --tries=3 --waitretry=10 --output-document=theme/themes.json https://monkeytype-readme.zeabur.app/mr-command/theme
        timeout-minutes: 10
      
      - name: Format JSON data
        run: |
          python3 -c 'import json; data = json.load(open("theme/themes.json")); json.dump(data, open("theme/themes.json", "w"), indent=2)'
      
      - name: Print json file contents
        run: cat theme/themes.json
        
      - name: Update theme list 
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            let monkeytypeThemesJson = fs.readFileSync('theme/themes.json');
            const filePath = '${{ github.workspace }}/theme/themes.json';
            fs.writeFileSync(filePath, monkeytypeThemesJson);
            
      - name: Print updated theme contents
        run: |
          cat theme/themes.json
          
      - name: Configure git
        run: |
          git config --global user.name "ridemountainpig"
          git config --global user.email "lin0905580802@gmail.com"
          
      - name: Commit and push changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected."
          else
            git add .
            git commit -m "feat: update themes json list"
          fi
        continue-on-error: true
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
